### ISSUE TITLE
Plugin has Exception when trying to import `EmulatorHelper`

### ISSUE THREAD

**Issue by deeso** [TheRomanXpl0it/ghidra-emu-fun#3]
**Describe the bug**
Emulator fails to find expected Python Packages.  Using Ghidra Version 9.0.4.

**To Reproduce**
1. Installed scripts as noted in the README
2. Ran the `emulate_function.py` from the Script Manager
3. See error
```
emulate_function.py> Running...
Traceback (most recent call last):
  File "research/ghidra-emu-fun/src/plugin.py", line 4, in <module>
    from plugin import EmulatorPlugin
  File "research/ghidra-emu-fun/src/plugin.py", line 9, in <module>
    from emulator import Emulator, EmulatorState
  File "research/ghidra-emu-fun/src/plugin.py", line 3, in <module>
    from ghidra.app.emulator import EmulatorHelper
ImportError: No module named emulator
emulate_function.py> Finished!
```

**Comment by chq-matteo** [comment]
I think those apis were introduced in 9.1.x, I'll check the exact version later

**Comment by chq-matteo** [comment]
Let me know if you hit any other issue, thank you for reporting this, I'll update the readme

**Comment by deeso** [comment]
Ah.  I updated to the latest version v9.1.2 Feb 2020, and the dialog is working now.  Thanks for the tip.
